### PR TITLE
I have applied Refactoring techniques on the project as I have got assignment from my university kindly look into my changes and accept the request in your feature branch 

### PR DESCRIPTION
**Pull request by jenishp619**
请提交至 **pre-release** 分支，勿直接提交至master分支。

请包含更改摘要以及修复的问题。还请包括相关的动机和背景。列出此更改所需的所有依赖项。

Please submit to the pre-release branch, do not submit directly to the master branch.

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

- [ ] Bug修复/Bug fix (non-breaking change which fixes an issue)
- [x] 新特性/New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by liaochong** [comment]
Thank you for submitting pull requests, but I'm sorry that the content you submitted does not meet the actual needs, so this submission will be abandoned. In myexcel version 4.0.1, there is a bug in the SaxExcelReader: in the doReadXls method, if the detectedMerge = true, but the mergecellIndexMapping is found to be empty after parsing, the detectedMerge should be set to false, otherwise a null pointer exception will be thrown. Can you help fix it?

**Comment by jenishp619** [comment]
okay i will look into it but will you accept the pull request in the
feature branch that I have already submitted?
https://github.com/liaochong/myexcel/pull/357 This is working well

**Comment by liaochong** [comment]
These two submissions are the same, so they won't be adopted. First look at the bug I said. It's very simple. I think you can fix it quickly, so I can merge it as soon as possible

**Comment by jenishp619** [comment]
So in order to accept my changes what should I do? Can you tell me what
changes should be made? And can you consider my changes for refactoring I
want bonus points for assignment so I am requesting you to guide me

**Comment by jenishp619** [comment]
Ok, will do that. So after that fix will you do my work for refactoring

**Comment by liaochong** [comment]
Isn't fixing bugs part of refactoring?

**Comment by jenishp619** [comment]
No, it doesn't. my assignment is to refactor the code in terms of
readability and duplication of code

**Comment by jenishp619** [comment]
on which branch should i send you pull request ?

**Comment by liaochong** [comment]
[Hotfix/4.0.2](https://github.com/liaochong/myexcel/tree/Hotfix/4.0.2).

Well, there are many things that need to be refactored, but this needs to be discussed. After you find the code that needs to be refactored, submit a small part or email to me to discuss whether it is necessary to refactor, so as to ensure that your work is effective, otherwise it may waste your time.

**Comment by jenishp619** [comment]
can you tell me exactly what file needs to be fixed and your problem again?

**Pull request closed without merging**
